- name: Install MySql database
  apt:
    name:
      - default-mysql-server
      - default-mysql-client
    state: present

- name: Start MySql server
  shell: /etc/init.d/mysql start

- name: Create mySql application db
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create mySql database user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    state: present
    host: '%'
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true