- name: Install python flask dependency
  pip:
    name: [ 'flask', 'flask-mysql' ]
    state: present

- name: Copy source code to target
  copy:
    src: source/app.py
    dest: /opt/app.py

- name: Start Web Server
  shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &